### ISSUE TITLE
When i import the package into my project,i got error,can't found Permission

### ISSUE THREAD

**Issue by ZhangX-Byte** [Firelands128/amap_flutter#1]
<img width="528" alt="截屏2024-03-30 13 56 32" src="https://github.com/Firelands128/amap_flutter/assets/6357361/e27b4cd2-d252-4c41-9539-a7c626c55764">

**Comment by SATTIRAMYASRI** [comment]
Hi @ZhangX-Byte ,
Did you made changes for android and ios files as the paclage suggests ?.

Please provide me the complete issue and what you did so that i can help you. 
Thank you

**Comment by ZhangX-Byte** [comment]
I address the issue

**Comment by ZhangX-Byte** [comment]
but when i run the example code,i got a div error,when my target is web

**Comment by Firelands128** [comment]
Since flutter version 3.19, onPlatformViewCreated callback function would be called before HTML element inserted to the DOM. That's why the error of Map container div not existed occurred. According to [Flutter issue #143922](https://github.com/flutter/flutter/issues/143922), I have implemented the workaround provided in ```Flutter issue #143922``` after amap_flutter version 0.1.0.
